server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}  # 環境変数から取得
    username: ${SPRING_DATASOURCE_USERNAME}  # 環境変数から取得
    password: ${SPRING_DATASOURCE_PASSWORD}  # 環境変数から取得
    driver-class-name: org.postgresql.Driver  # PostgreSQLのドライバ指定
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Dialect の明示的指定
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}  # 環境変数から取得
    user: ${SPRING_DATASOURCE_USERNAME}  # 環境変数から取得
    password: ${SPRING_DATASOURCE_PASSWORD}  # 環境変数から取得
    locations: classpath:db/migration
    baseline-on-migrate: true
