server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}  # 環境変数 DATABASE_URL がなければデフォルト値を使用
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:JXNSUDzebwxrxplYtsNxoNPOoMgEtKga}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    url: ${DATABASE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:JXNSUDzebwxrxplYtsNxoNPOoMgEtKga}
    locations: classpath:db/migration
    baseline-on-migrate: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret:
    key: ${JWT_SECRET:myWebAppQuizKey12345678901234567890123456789012}  # JWT_SECRETが設定されない場合のデフォルト

gemini:
  api:
    key: ${GEMINI_API_KEY}  # 必ず環境変数 GEMINI_API_KEY を設定する

logging:
  file:
    name: logs/app.log
  level:
    org.springframework.security: DEBUG
    com.example.myapp: DEBUG
